name: Export upmpdcli Docker Image (ARM64)

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull image (linux/arm64)
      run: |
        docker pull --platform linux/arm64 giof71/upmpdcli:debian-stable-renderer
        docker save giof71/upmpdcli:debian-stable-renderer -o upmpdcli.tar
        ls -lh upmpdcli.tar

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: upmpdcli-export
        tag_name: export-${{ github.run_id }}
        files: upmpdcli.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
